posthtml/posthtml

lib/posthtml.js
test/set-options.js

Resolve #2 
cc/ @posthtml/owners

feature(*): add skipParse options

---

lib/posthtml.js
test/options.js
test/plugins.js
test/test.js

feature(*): deep results objects

---

.gitignore
.travis.yml
README.md
gulpfile.babel.js
package.json

[WIP] feature(*): add-travis-and-coverage

---

lib/posthtml.js

Hey guys! Sorry if I'm annoying, but I'd added some es6 goodies to your awesome code :D

add moar es6 things

---

lib/posthtml.js
test/plugins.js

It's like postcss. Just update tree without any return.

fix plugin needs return json

---

README.md
gulpfile.babel.js
lib/api.js
lib/parser.js
lib/posthtml.js
test/api.js
test/comments.js
test/doctype.js
test/plugins.js
util/test.js

feat(api): base API

---

.jscsrc
gulpfile.babel.js
lib/api.js
lib/parser.js
lib/posthtml.js
package.json
test/options.js
test/plugins.js

feat(lint): own jscs config

---

README.md
lib/api.js
lib/posthtml.js
package.json
test/init.js
test/mocha.opts
test/plugins.js

- implement truly sync and async modes
- tests for them
- rework tests for Plugins
/cc @voischev @awinogradov 
Fixes #52

Sync and async modes

---

README.md
lib/api.js
test/api.js

feat(api): support RegExp matchers

---

README.md

added link to posthtml-match-helper

---

lib/api.js
test/api.js

feat(api): chaining

---

README.md

made changes to README

---

README.md

changed README to add link to grunt-posthtml

---

README.md

I think this helper might be useful for other developers. It gives a better API to work with tag's attrs.

Add posthtml-attrs-parser to helpers

---

lib/api.js
test/api.js

fix(api): fix binds tree for import API

---

README.md

Source: https://github.com/mrmlnc/posthtml-attrs-sorter/issues/1

Add posthtml-attrs-sorter to the plugins list

---

lib/posthtml.js
test/plugins.js

Fix promise check

---

CHANGELOG.md
README.md
docs/API.md
docs/Helpers.md
docs/Plugins.md
docs/Tree.md
lib/posthtml.js
package.json
test/plugins.js

README updates

---

lib/api.js
lib/posthtml.js

1. Remove couple extra functions.
2. Do not cache `.length`. VMs are able to detect loop invariants.
3. Simplify `isPromise`: do not check for object. `then` on primitives prototypes is extremely unlikely.

Minor refactoring

---

.jshintrc
lib/api.js
lib/posthtml.js
package.json
test/api.js
test/init.js
test/plugins.js

1. Corrected typos, grammar, js syntax, and code style in doc blocks.
2. Added strict mode declarations. Why? Performance (`UnmappedArguments`), less silent errors.
3. Simplified `tryCatch` helper.
4. [Removed slice call](https://github.com/posthtml/posthtml/commit/8a3ff116e4c0fc3cb1308e1ca7a436a3ab080e16); invoke`some` directly on array(like), without an extra array.
5. Removed jshints `global` instructions for `Promise`. These instructions are more suited for listing user-defined variables, not stdlib or environments APIs.
6. Installed `Object.assign` as polyfill. There is no reason to use, eg. `Object.keys` directly, but ponyfill `Object.assign`.

Couple more improvements

---

README.md

URL for that plugin was broken.

Fix typo in Plugins->posthtml-hint URL

---

test/api.js

This test ensures that when given an array of expressions, `match` will invoke callback only once, even if multiple expressions were matched.

Add test for multiple matches

---

.gitignore
README.md

Info about plugin
https://github.com/posthtml/posthtml-plugin-boilerplate/pull/4#issuecomment-250979096

posthtml-webp

---

MAINTAINERS

chore(*): delete MAINTAINERS file

---

lib/index.js

It is necessary to determine the exact name of the processor.
Now it's not obvious - https://github.com/post-org/post-load-plugins/blob/master/src/post-processor.js

To determine the name of the processor

---

README.md

add rollup example

---

lib/index.js
test/api.js
test/plugins.js

fixes #224 errors from plugins now returned

---

package.json

chore(package): use `files` to reduce package size

---

README.md

fix(readme): adds missing bracket

---

README.md

Documentation only, adds [posthtml-highlight](https://github.com/caseyWebb/posthtml-highlight) to README

docs(README): add `posthtml-highlight`

---

README.md

Added a link to the prevent-widows package
```
added prevent-widows plugin to README.md
```

added prevent-widows plugin to README.md

---

README.md

updated readme to add favicons generator package
- Fixes `#1`

Add link to posthtml-favicons

---

docs/api.md

```
commit message body...
```
- Fixes `#1`
> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is a reminder of what we are …

Clarify code a little

---

README.md

[docs]: Broken links in README

---

README.md

Adding from request of @Scrum
```
Add posthtml-minify-classnames to plugins list
```
> ℹ️  Adding a plugin
patch?

Add posthtml-minify-classnames to plugins list

---

README.md

> Adding [posthtml-pseudo](https://github.com/kevinkace/posthtml-pseudo) to list of HTML plugins.
```
Add posthtml-pseudo
```
- N/A

Add posthtml-pseudo

---

CHANGELOG.md
docs/api.md
lib/api.js
package.json
test/api.js
test/plugins.js

* **perf:** Add TypeScript typings ([89bf763](https://github.com/posthtml/posthtml/commit/89bf763q))
* **plugin:** Add posthtml-minify-classnames ([9844a08](https://github.com/posthtml/posthtml/commit/9844a08))
* **plugin:** Add posthtml-pseudo ([8b86f58](https://github.com/posthtml/posthtml/commit/8b86f58))
* **plugin:** Add posthtml-lazyload ([1009bff](https://github.com/posthtml/posthtml/commit/1009bff))
* **plugin:** Add posthtml-link-noreferrer ([1009bff](https://github.com/posthtml/posthtml/commit/1009bff))
> ℹ️  You can also fill …

Milestone 0.11.5

---

CHANGELOG.md
package.json

* typings ([97d89ad](https://github.com/posthtml/posthtml/commit/97d89ad))
* **typings:** Type-inference for node.prototype.match ([90d3c48](https://github.com/posthtml/posthtml/commit/90d3c48))

Milestone 0.11.6

---

CHANGELOG.md
README.md
docs/core.md
docs/plugins/index.md
lib/index.js
package.json
test/core.js
test/plugins.js

Milestone 0.12.0

---

README.md

Add posthtml-inline-svg to IMG & SVG plugins.
```
docs(README): Add posthtml-inline-svg
```

docs(README): Add posthtml-inline-svg

---

README.md

Add posthtml plugins to list of plugins in README.md.
- `posthtml-noopener`
- `posthtml-noscript`
- `posthtml-inline-favicon`
- `posthtml-hash`
- `posthtml-insert-at`
```
Update plugin list in README.md.
```
- [x ] Docs
- [x ] Fix (:label: Patch)
> 👉  _Replace `#1` with the …

docs(readme): add posthtml plugins to plugin list

---

README.md

Added 2 new plugins in the readme

add plugin-link-preload, plugin-remove-duplicates

---

.editorconfig
README.md
docs/api.md
docs/plugins/index.md

Fix docs code formatting

---

README.md

Adds [`posthtml-prism`](https://github.com/posthtml/posthtml-prism) to HTML plugins list in README.md.

Add posthtml-prism to plugins list.

---

README.md
docs/plugins/guide.md
docs/plugins/index.md

```
- docs: update links and phrasing adjustments
```
- Relates https://github.com/posthtml/posthtml.org/pull/8
> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of …

docs: update links and phrasing adjustments

---

CHANGELOG.md
lib/index.js
package.json
test/source.js

- drop support old node
- source in tree
```
build: drop support old node
test: for source, issue #243
feat: source in tree, close issue #243 
```
- Feature `#243`
> 👉  _Put an `x` in the boxes that apply and delete all …

Milestone 0.13.0

---

README.md

Added a few more plugins to the README.

Add new plugins to README

---

README.md

added `posthtml-postcss-treeshaker` to optimizing table
docs (readme)
- Fixes `#1`
> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

docs: added posthtml-postcss-treeshaker to optimizing table

---

README.md

https://github.com/Grawl/posthtml-richtypo/issues/1

add posthtml-richtypo to readme

---

README.md

```
Add plugin PostHTML-TOC
```

Add plugin PostHTML-toc

---

CHANGELOG.md
docs/core.md
lib/index.js
package.json

```
Add description for directives option
```

Milestone 0.13.2

---

test/api.js
test/classes.js
test/comments.js
test/core.js
test/doctype.js
test/init.js
test/messages.js
test/options.js
test/parser.js
test/plugins.js
test/process.js
test/source.js
test/test.js
test/text.js

Similar to #336. This time test has been migrated to ES6.
```
test: migrate to ES6
```
> 👉  _Replace `#1` with the issue number that applies and removes the ``` ` ```_
- Fixes `#1`

test: migrate to ES6

---

README.md

I read that it was recommended to [publicize new plugins here too](https://github.com/Grawl/posthtml-richtypo/issues/1). So I'm adding my new plugin.
Add posthtml-sri in plugin section
> 👉  _Put an `x` in the boxes that …

Add posthtml-sri in plugin section

---

lib/api.js
package.json

Milestone 0.14.0

---

README.md

Add a new posthtml plugin to README's plugin list.
```
docs: add posthtml-external-link to the plugin list
```

docs: add posthtml-external-link to plugin list

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push
.huskyrc
package.json

fixes husky hooks (broken since https://github.com/posthtml/posthtml/pull/362)
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7

build: fix husky hooks
